### ISSUE TITLE
Scaling costs

### ISSUE THREAD

**Issue by SeraphinEveles** [TalicZealot/SotnRandoTools#12]
# Is your feature request related to a problem? Please describe.
Some effects (namely krelics and pandora) can be stocked an used repeatedly, and with enough viewers can prevent a run from finishing

# Describe the solution you'd like
A possible option to make effects (toggleable per effect) scale based on # of times used (i.e., +10% per use, or +X per use)

# Describe alternatives you've considered
Cooldowns work, but lock things out for the duration, which can potentially cause a softlock/reset situation.

# Additional context
-

**Comment by TalicZealot** [comment]
I planned some kind of scaling system from the start, but then it turned out that the bot was the most straight forward way to handle currency. For now cooldowns are the recommended solution. Heavy help can prevent softlocks. In the future there may be a script for the chat bot that accompanies the tool for Khaos.

**Comment by TalicZealot** [comment]
Command cost scaling has been introduced in 1.0.0
